---
title: Вибери зображення з бібліотеки
hero_image: images/banner.png
description: Вибери зображення з бібліотеки.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Вибери зображення з бібліотеки
