title: Choose an image from the library
hero_image: images/banner.png
description: Choose an image from the library.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Choose an image from the library
