title: Choisir une image dans la bibliothèque
hero_image: images/banner.png
description: Choose an image from the library.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Choisir une image dans la bibliothèque
